### ISSUE TITLE
[DEV] Add console level manipulation to variable bit sizes

### ISSUE THREAD

**Issue by ArgosOfIthica** [ArgosOfIthica/scalu#10]
**Is your feature request related to a problem? Please describe.**
Users are currently unable to manipulate bit size so vars can have between 2 and an arbitrary amount of bits, though the codebase currently supports this. The default is 8, but many problems and scripts can be solved with less bits and will yield a significantly smaller footprint as well as slightly increased performance. You could also have larger vars, though I can't imagine what kind of monstrosity needs more than 8 bits of state in a key binding language.

**Describe the solution you'd like**
I would like users to have the option to override this option at the console level as a flag. `--bit=8` being the default.

**Describe alternatives you've considered**
This feature could be implemented as a language level construct, but that I'd essentially have to develop a type system to manage the interaction of different bit sizes, which is currently out of scope.

**Comment by ArgosOfIthica** [comment]
I am no longer interested in exposing this functionality to endusers. An 8 bit width should be ubiquitous. It will be possible in the future to silently cast to a narrower width as an optimization in the future, but only the compiler will have this power, and will only use it under certain conditions.

**Comment by tmob03** [comment]
> I am no longer interested in exposing this functionality to endusers. An 8 bit width should be ubiquitous. It will be possible in the future to silently cast to a narrower width as an optimization in the future, but only the compiler will have this power, and will only use it under certain conditions.

Why? Why not allow a variables to use anything other than 8 bits?

**Comment by ArgosOfIthica** [comment]
For the original vision of scalu, the cons just outweighed the pros. Different bit sizes breaks script interop, decrease performance, and bloat the generated code for little gain to the original imagined use cases; 8 bit was already more than enough for that.

I've moved on language level restrictions like this in the past year. Scalu's frontend was designed as a DSL, but when I see what scripts people are writing, they're not as interested in the frontend keybinding part as much as the backend compute part. Therefore, the new path I'm currently working towards is building up a strong backend that is very decoupled from the frontend. This way I can write a backend that is very permissive, general, and powerful, and then any particular language frontend can rein that in as much as it wants.

So I'm probably open to an option to change the global size for the near term; beyond that, I need to overhaul the backend first to entertain the idea of multiple interacting data types, whatever that looks like on any particular frontend.

**Comment by ArgosOfIthica** [comment]
Added flag `forcewordsize` in https://github.com/ArgosOfIthica/scalu/commit/2bed4c3f2d4765cf180d797b9f53324578a311b5

This will force the maximum variable size to be whatever number of bits you set it to. The compiler will still attempt to downcast to a smaller size where possible if its not possible for you to know its doing it. The minimum size is 2 bits. Not recommended or supported for scripts intended for seamless merging with other scripts, but if you want to make a weird one-off, its there.
