### ISSUE TITLE
[BUG] Compiling bit AND operation with a variable and constant causes an AttributeError.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [ArgosOfIthica/scalu#16]
**Describe the bug**
If an AND operation is performed on a variable with a constant, then the compiler returns `AttributeError: 'variable' object has no attribute 'is_constant'`.

**Program that produces bug**
testvar1 = 5
testvar = testvar1 & 2

**Expected behavior**
Successful compilation.

**Environment (please complete the following information):**
 - OS: Windows 10 10.0.19042 Build 19042
 - Game: TF2 as of the January 8, 2021 patch.
 - Version of Compiler: latest version copied from master branch.

**Additional context**
If an AND operation is performed on a variable with a variable, the no compilation error occurs.

My python version is Python 3.8.3.

EDIT: This bug seems to also be occurring for the bit OR operations as well.

**Comment by ArgosOfIthica** [comment]
Thanks for the detailed bug report! Feature testing will now check that this is working properly from now on. I've fast tracked this to master.

#17
