### ISSUE TITLE
[FEATURE] Add escapes to source commands

### ISSUE THREAD

**Issue by ArgosOfIthica** [ArgosOfIthica/scalu#37]
**Is your feature request related to a problem? Please describe.**
When executing a source command,

`[my_command]`

there is no way to express a closing brace `]`.

**Describe the solution you'd like**
Add an escape character `\` to denote the next character should be escaped. Notably, this means the escape character will need to be escaped to be expressed literally going forward.

**Comment by ArgosOfIthica** [comment]
@tmob03

**Comment by ArgosOfIthica** [comment]
@tmob03 Github doesn't let me assign this to you unless you respond here, even despite you creating a pull request. `¯\_(ツ)_/¯`

**Comment by tmob03** [comment]
Odd, I'll look at this later today.
