### ISSUE TITLE
[FEATURE] GLua implementation of Scalu (“Scalua”?)

### ISSUE THREAD

**Issue by chexo3** [ArgosOfIthica/scalu#41]
**Is your feature request related to a problem? Please describe.**
I believe a GLua implementation of Scalu’s compiler could be useful for Garry’s Mod, for example for configuring addons. 

**Describe the solution you'd like**
A library for inclusion into Garry’s Mod for the purposes of configuring addons.

**Describe alternatives you've considered**
I could maybe make something hacky myself, but I lack familiarity with the code base, and I think this feature would interest you anyways.

**Additional context**
I’m working on a project this would be useful for.

**Comment by tmob03** [comment]
You’re asking for the compiler to be rewritten in Lua? With gmod, can’t you do everything and more than just configuration files?

**Comment by chexo3** [comment]
No, I meant that having access to the Scalu compiler in Gmod as a compiler would be useful for addon development. Think about it: it’s an abstraction over state machines made with source config files, and so normally it compiles to those, but who says it has to? I could use the same syntax for configuring an addon, for example.

**Comment by ArgosOfIthica** [comment]
lol "Scalua"

So to clarify, you want Scalu to produce GLua specific output/artifacts? I'm unfamiliar with this usecase, could you produce a small example of something you'd imagine might be helpful?

**Comment by chexo3** [comment]
No, I should clarify. I want to have an implementation of the Scalu compiler in Lua, so that an addon can parse Scalu files for it’s configuration. The finite state machine aspect would be useful for the use case I have where I want to be able to let folks write scripts to hook up events on the server to actions. So for my first use case I have in mind, it would respond to a round start event fired by some code hooking into TTT2 and then run code to iterate through the list of players and blacklist ArcCW attachments depending on their role. But I want to make something I can re-use for other use cases. (I could just hard code the behavior I want into an addon, but that would be a pain to change for balance as my TTT group plays with the addon).

So another example could be for a DarkRP server: Blacklisting certain props based on which job a player has.

Scalu’s finite state machine model may have originally been intended for compiling to .cfg files, and indeed I could still use it that way to generate cfg files at runtime, but I also think it would be useful for this sort of configuration too. So actually yeah, being able to output GLua would be useful, but I’d like to be able to do so at runtime. Maybe we could look at how Expression 2 does it?

**Comment by ArgosOfIthica** [comment]
OK, I think I see what you're getting at. If Scalu's broader model is what you like, then I would personally recommend just emulating that pattern in GLua. Most of Scalu's codebase isn't even about Scalu semantics (the frontend), but rather transforming them into an equivalent and performant cfg program (the backend). I'd definitely encourage you to take the ideas you like and make a thing focused on what you want without tying yourself to the syntax and semantics originally designed to wrangle the mess that is cfg scripting.

I broadly think rewriting Scalu in GLua or intermingling too deeply with GLua is outside of scope for me. The only caveat is if there's some kind of utility or dynamism or features you could get by bridging cfg with lua, like programmatically running `lua_openscript` or something, and there's some kind of language feature that would help for doing so.

`So actually yeah, being able to output GLua would be useful, but I’d like to be able to do so at runtime. Maybe we could look at how Expression 2 does it?`

Theoretically very easily done if you have a self-hosted Lua implementation (Lua interpreter written in Lua) somewhere.

**Comment by ArgosOfIthica** [comment]
Going to go ahead and close this, I don't think I can personally put resources into something like this for the reasons outlined. Feel free to start a PR if you'd like to tackle it yourself.

**Comment by chexo3** [comment]
No worries. I should probably just make a more generalized state machine library for GLua.
